knp_menu:
    twig: true  # set to false to disable the Twig extension and the TwigRenderer
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default

