imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    translator:       ~
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        #auto_mapping: true
        entity_managers:
            default:
                mappings:
                    KunstmaanKAdminBundle: ~
                    KunstmaanKCoreBundle: ~
                    FOSUserBundle: ~
                    #AnoMediaBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb'
    firewall_name: main
    user_class: Kunstmaan\KAdminBundle\Entity\User
    resetting:
        token_ttl: 86400
        email:
            from_email: # Use this node only if you don't want the global email address for the resetting email
                address:        admin@kunstmaan.be
                sender_name:    admin
            template:   FOSUserBundle:Resetting:email.txt.twig
        form:
            type:               fos_user_resetting
            handler:            fos_user.resetting.form.handler.default
            name:               fos_user_resetting_form
            validation_groups:  [ResetPassword]

ano_media:
    cdn:
        local:
            default: true
            id: ano_media.cdn.remote_server
            options:
                base_url: "http://omnext.echo.kunstmaan.be/" # instellen in parameters.ini?

    provider:
        image:  # So we need the image provider here
            default: true
            id: ano_media.provider.image
        file:  # So we need the image provider here
            default: false
            id: ano_media.provider.file


    filesystem:
            local:
                default: true
                id: ano_media.filesystem.local
                options:
                    base_path: %kernel.root_dir%/../web/uploads/media
                    create: true  #creates the directory if it doesn't exist yet

    contexts:
        omnext_picture:
            provider: image
            formats:
                small: { width: 90, height: 90 }
                medium: { width: 210, height: 150 }
                large: { width: 330, height: 230 }

        omnext_file:
            provider: file


