imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @KunstmaanMediaBundle/Resources/config/config.yml }
    - { resource: @KunstmaanAdminBundle/Resources/config/config.yml }
    - { resource: @KunstmaanNodeBundle/Resources/config/config.yml }
    - { resource: @KunstmaanFormBundle/Resources/config/config.yml }
    - { resource: @KunstmaanSearchBundle/Resources/config/config.yml }
    - { resource: @KunstmaanAdminListBundle/Resources/config/config.yml }

framework:
    esi:             true
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~
        #storage_id: session.storage.pdo ## disabled because you need to manually create the table after fullreload. fix could be creating an entity for this table. see symfony.com/doc/current/cookbook/configuration/pdo_session_storage.html

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        websitetitle: %websitetitle%
        defaultlocale: %defaultlocale%
        requiredlocales: %requiredlocales%
        #titlecolor: "#000000"
        #titlebgcolor: "#F53111"
        #ga_code: %ga_code% ## don't forget to specify this parameter in parameters.yml

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ "KunstmaanAdminBundle", "KunstmaanAdminListBundle" ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/tools/java/yuicompressor-2.4.7.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/tools/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                metadata_cache_driver: apc
                result_cache_driver: apc
                query_cache_driver: apc
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                        alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # this one is optional and will default to the name set for the mapping
                        is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

parameters:
    #pdo.db_options:
    # db_table: session
    # db_id_col: session_id
    # db_data_col: session_value
    # db_time_col: session_time

stof_doctrine_extensions:
    default_locale: nl
    translation_fallback: true
    orm:
        default:
           loggable: true
           translatable: true
           sluggable: true

liip_imagine:
    cache_prefix: uploads/cache
    driver: imagick
    #cache: no_cache
    filter_sets:
        thumb_image_block_1:
            quality: 75
            filters:
                thumbnail: { size: [310, 229], mode: outbound }
        thumb_image_block_2:
            quality: 75
            filters:
                thumbnail: { size: [630, 229], mode: outbound }

liip_cache_control:
    rules:
        - { path: /admin, controls: { private: true, max_age: 0} }
        - { path: ^/_internal, controls: {private: true, max_age: 0} }
        - { path: ^/(.+), controls: { public: true, max_age: 120, s_maxage: 240 }, vary: [Cookie,Accept-Encoding] }

services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

    monitor.check.deps_entries:
        class: Liip\MonitorExtraBundle\Check\DepsEntriesCheck
        arguments:
            - %kernel.root_dir%
        tags:
            - { name: monitor.check }

    monitor.check.symfony_version:
        class: Liip\MonitorExtraBundle\Check\SymfonyVersionCheck
        tags:
            - { name: monitor.check }

    #pdo:
    # class: PDO
    # arguments:
    # - "mysql:dbname=%database_name%"
    # - %database_user%
    # - %database_password%

    #session.storage.pdo:
    # class: Symfony\Component\HttpFoundation\SessionStorage\PdoSessionStorage
    # arguments: [@pdo, %session.storage.options%, %pdo.db_options%]

    kunstmaan_logging_introspection:
        class: Monolog\Processor\IntrospectionProcessor
        tags:
            - { name: monolog.processor }

    kunstmaan_logging_web:
        class: Symfony\Bridge\Monolog\Processor\WebProcessor
        tags:
            - { name: monolog.processor }

    kunstmaan_logging_formatter:
        class: Monolog\Formatter\LineFormatter
